### ISSUE TITLE
Page points to invalid URL of Digipolis Antwerp Open API Generator

### ISSUE THREAD

**Issue by webdevotion** [digipolisantwerpdocumentation/api-system#1]
[Page](https://acpaas-api.digipolis.be/#/content/tools/generators) points to invalid URL of Digipolis Antwerp Open API Generator:

<img width="562" alt="Screenshot 2021-06-09 at 10 40 26" src="https://user-images.githubusercontent.com/50583/121322251-1c372300-c90f-11eb-87e1-8a1eeef80ef8.png">

Page = https://acpaas-api.digipolis.be/#/content/tools/generators.

**Comment by webdevotion** [comment]
https://github.com/digipolisantwerpdocumentation/api-system/edit/master/docs/content/tools/generators.md

**Comment by PeterClaes** [comment]
> [Page](https://acpaas-api.digipolis.be/#/content/tools/generators) points to invalid URL of Digipolis Antwerp Open API Generator:
> 
> <img alt="Screenshot 2021-06-09 at 10 40 26" width="562" src="https://user-images.githubusercontent.com/50583/121322251-1c372300-c90f-11eb-87e1-8a1eeef80ef8.png">
> 
> Page = https://acpaas-api.digipolis.be/#/content/tools/generators.

**Comment by eriklenaerts** [comment]
hey, @PeterClaes 

Je mag hier naar verwijzen. er kan ook gerust een fork gemaakt worden onder de digipolisantwerpdocumentation. Ga wel enkel m'n eigen repo onderhouden ;). Zou zeggen, voorlopig even naar mijn rep verwijzen, als het straks wat stabieler is, kunnen we nog de link verleggen ;)

generator: https://github.com/eriklenaerts/openapi-generator

**Comment by PeterClaes** [comment]
done : link naar EL repo
